services:
  db:
    image: postgres:15
    container_name: wikijs_postgres
    restart: always
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs2025
    volumes:
      - db_data:/var/lib/postgresql/data

  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs2025
      DB_NAME: wikijs

volumes:
  db_data: